### ISSUE TITLE
"msecs must be a number" when using the --timeout option.

### ISSUE THREAD

**Issue by ozomer** [alexfernandez/loadtest#92]
I guess the command argument is not converted from a string to a number.

**Comment by alexfernandez** [comment]
What version and command line are you running exactly? I am unable to reproduce the error. I found an unrelated bug and fixed it in 1.3.2 though, so please run that and report back.

**Comment by ozomer** [comment]
I installed version 1.3.0 from npm.
Please update the package on npm.

**Comment by ozomer** [comment]
When will you release version 1.3.2 to npm?

**Comment by alexfernandez** [comment]
Done, sorry!

**Comment by cmaart** [comment]
Is this happening again? I am on version 1.4.3 and my call looks like this:
`loadtest -k --timeout 1000 http://localhost:xxx/yyyy`

**Comment by alexfernandez** [comment]
@cmaart Works for me locally, what OS are you on?

**Comment by brezinajn** [comment]
version 1.4.4 
win 10 64bit
loadtest --timeout 600 http://localhost:3000/
still happening

**Comment by alexfernandez** [comment]
Odd, let me look into it.

**Comment by alexfernandez** [comment]
@brezinajn I found a bug and [corrected it](https://github.com/alexfernandez/loadtest/commit/09470ae02b40e74e88f39814e2190b3bf92a3a60), please retest with 1.4.5, just published.

**Comment by brezinajn** [comment]
On both 1.4.5 and 2.0.0 I get

```events.js:295
    throw new TypeError('"listener" argument must be a function');
    ^

TypeError: "listener" argument must be a function
    at ClientRequest.once (events.js:295:11)
    at ClientRequest.setTimeout (_http_client.js:610:22)
    at HttpClient.self.makeRequest (C:\Users\than\AppData\Roaming\npm\node_modules\loadtest\lib\loadtest.js:210:12)
    at HttpClient.self.start (C:\Users\than\AppData\Roaming\npm\node_modules\loadtest\lib\loadtest.js:144:16)
    at startClients (C:\Users\than\AppData\Roaming\npm\node_modules\loadtest\lib\loadtest.js:465:12)
    at self.start (C:\Users\than\AppData\Roaming\npm\node_modules\loadtest\lib\loadtest.js:413:3)
    at Object.exports.loadTest (C:\Users\than\AppData\Roaming\npm\node_modules\loadtest\lib\loadtest.js:378:12)
    at Object.<anonymous> (C:\Users\than\AppData\Roaming\npm\node_modules\loadtest\bin\loadtest.js:138:10)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)

**Comment by alexfernandez** [comment]
Can you please send me the trace for 2.0.0? The bug in 1.4.5 (shown in your current trace) was solved, there must be another one.

**Comment by brezinajn** [comment]
stack trace from v 2.0.0
```events.js:295
    throw new TypeError('"listener" argument must be a function');
    ^

TypeError: "listener" argument must be a function
    at ClientRequest.once (events.js:295:11)
    at ClientRequest.setTimeout (_http_client.js:610:22)
    at HttpClient.self.makeRequest (C:\Users\than\AppData\Roaming\npm\node_modules\loadtest\lib\httpClient.js:211:12)
    at HttpClient.self.start (C:\Users\than\AppData\Roaming\npm\node_modules\loadtest\lib\httpClient.js:145:16)
    at startClients (C:\Users\than\AppData\Roaming\npm\node_modules\loadtest\lib\loadtest.js:176:12)
    at self.start (C:\Users\than\AppData\Roaming\npm\node_modules\loadtest\lib\loadtest.js:120:3)
    at Object.exports.loadTest (C:\Users\than\AppData\Roaming\npm\node_modules\loadtest\lib\loadtest.js:85:12)
    at Object.<anonymous> (C:\Users\than\AppData\Roaming\npm\node_modules\loadtest\bin\loadtest.js:138:10)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
`

**Comment by alexfernandez** [comment]
OK, another stupid bug! Found and corrected it, should be fixed in 2.0.1. Please retry and let me know how it goes!

**Comment by brezinajn** [comment]
stacktrace from v2.0.1 (it didn't ping the server)

```
[Wed Sep 14 2016 14:07:42 GMT+0200 (Central Europe Daylight Time)] INFO Requests: 0, requests per second: 0, mean latency: 0 ms
timers.js:285
    throw new TypeError('"msecs" argument must be a number');
    ^

TypeError: "msecs" argument must be a number
    at Object.exports.enroll (timers.js:285:11)
    at Socket.setTimeout (net.js:321:12)
    at ClientRequest.<anonymous> (_http_client.js:636:10)
    at ClientRequest.g (events.js:286:16)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at tickOnSocket (_http_client.js:562:7)
    at onSocketNT (_http_client.js:574:5)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
`

**Comment by alexfernandez** [comment]
In 2.0.2 I am converting to a number, please try it and report back. Thanks for your patience in tracking this #&%! bug!

**Comment by brezinajn** [comment]
It's working :). Thank you for your effort. It's highly appreciated.

**Comment by alexfernandez** [comment]
Good to know, closing.

**Comment by ankitacroit09** [comment]
How to fix the issue.
